import { Inter } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';
import LeftSideBar from "@components/layout/LeftSideBar";
import MainContainer from "@components/layout/MainContainer";
import Topbar from "@components/layout/TopBar";
import RightSideBar from "@components/layout/RightSideBar";

import "../globals.css";


interface Metadata {
  title: string;
  description: string;
}

interface RootLayoutProps {
  children: React.ReactNode;
}

const metadata: Metadata = {
  title: 'Zone',
  description: 'Generated by Next.js',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={`${inter.className} bg-purple-2`}>
        <LeftSideBar/>
        <MainContainer>
          <Topbar/>
        {children}
        </MainContainer>
        <RightSideBar/>
        </body>
      </html>
    </ClerkProvider>
  );
}
