import { Inter } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';
import "../globals.css";


interface Metadata {
  title: string;
  description: string;
}

interface RootLayoutProps {
  children: React.ReactNode;
}

const metadata: Metadata = {
  title: 'Auth',
  description: 'Generated by Next.js',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} bg-purple-2`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
